-- Crear tabla de productos
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL,
  inventory INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Políticas para products
-- 1. Todos pueden ver los productos
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.products FOR SELECT
  USING ( true );

-- 2. Solo administradores pueden insertar
CREATE POLICY "Admins can insert products."
  ON public.products FOR INSERT
  WITH CHECK ( auth.jwt() -> 'user_metadata' ->> 'role' = 'admin' );

-- 3. Solo administradores pueden actualizar
CREATE POLICY "Admins can update products."
  ON public.products FOR UPDATE
  USING ( auth.jwt() -> 'user_metadata' ->> 'role' = 'admin' );

-- 4. Solo administradores pueden eliminar
CREATE POLICY "Admins can delete products."
  ON public.products FOR DELETE
  USING ( auth.jwt() -> 'user_metadata' ->> 'role' = 'admin' );

-- Insertar el usuario administrador con la clave "12345678Cecyte"
-- Nota: En Supabase, para insertar usuarios de autenticación desde SQL, usamos crypt y auth.users
DO $$
DECLARE
  new_user_id UUID := gen_random_uuid();
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'admin@floreriaash.com') THEN
    INSERT INTO auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      recovery_sent_at,
      last_sign_in_at,
      raw_app_meta_data,
      raw_user_meta_data,
      created_at,
      updated_at,
      confirmation_token,
      email_change,
      email_change_token_new,
      recovery_token
    )
    VALUES (
      '00000000-0000-0000-0000-000000000000',
      new_user_id,
      'authenticated',
      'authenticated',
      'admin@floreriaash.com',
      crypt('12345678Cecyte', gen_salt('bf')),
      now(),
      now(),
      now(),
      '{"provider": "email", "providers": ["email"]}',
      '{"role": "admin"}',
      now(),
      now(),
      '',
      '',
      '',
      ''
    );

    INSERT INTO auth.identities (
      id,
      user_id,
      identity_data,
      provider,
      provider_id,
      last_sign_in_at,
      created_at,
      updated_at
    )
    VALUES (
      gen_random_uuid(),
      new_user_id,
      format('{"sub": "%s", "email": "admin@floreriaash.com"}', new_user_id)::jsonb,
      'email',
      new_user_id::text,
      now(),
      now(),
      now()
    );
  END IF;
END $$;

-- Crear tabla de orders
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  payment_method_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Políticas para orders
-- Los usuarios pueden ver sus propias órdenes
CREATE POLICY "Users can view their own orders."
  ON public.orders FOR SELECT
  USING ( auth.uid() = user_id );

-- Los usuarios pueden insertar sus propias órdenes (o anónimas si permitimos compras sin cuenta)
CREATE POLICY "Anyone can insert orders."
  ON public.orders FOR INSERT
  WITH CHECK ( true );

-- Los administradores pueden ver todas las órdenes
CREATE POLICY "Admins can view all orders."
  ON public.orders FOR SELECT
  USING ( auth.jwt() -> 'user_metadata' ->> 'role' = 'admin' );

-- Insertar productos demo
INSERT INTO public.products (name, price, image, inventory)
VALUES 
  ('Ramo Primaveral', 450, 'https://images.unsplash.com/photo-1563241598-6dc3a964063f?q=80&w=600&auto=format&fit=crop', 10),
  ('Rosas Eternas', 800, 'https://images.unsplash.com/photo-1582791694770-bd600642cebf?q=80&w=600&auto=format&fit=crop', 10),
  ('Caja de Tulipanes', 650, 'https://images.unsplash.com/photo-1520764816124-749e7552debc?q=80&w=600&auto=format&fit=crop', 10),
  ('Peonías Rosas', 900, 'https://images.unsplash.com/photo-1568867597148-73b342416b9b?q=80&w=600&auto=format&fit=crop', 10),
  ('Girasoles Sol', 550, 'https://images.unsplash.com/photo-1559868669-e05fae3e4a3c?q=80&w=600&auto=format&fit=crop', 10),
  ('Orquídea Elegante', 1200, 'https://images.unsplash.com/photo-1568212108740-10901e9be615?q=80&w=600&auto=format&fit=crop', 10)
ON CONFLICT DO NOTHING;
